/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ButovskyNFT__factory } from "./ButovskyNFT__factory";
export { WavePortal__factory } from "./WavePortal__factory";
