/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as contracts from "./contracts";
export type { contracts };
export type { ButovskyNFT } from "./contracts/ButovskyNFT";
export type { WavePortal } from "./contracts/WavePortal";
